project_id = "vamgjaitoiuitvlwqoic"

[functions.mp-webhook]
verify_jwt = false

[functions.mp-create-subscription]
verify_jwt = true

[functions.notify-new-user]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = true

